# Generated by Django 3.2 on 2021-09-02 15:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Calendar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField()),
                ('HCLprice', models.FloatField(blank=True, default=0)),
                ('HCRprice', models.FloatField(blank=True, default=0)),
                ('HMprice', models.FloatField(blank=True, default=0)),
                ('FyGprice', models.FloatField(blank=True, default=0)),
                ('NHprice', models.FloatField(blank=True, default=0)),
                ('HCLrooms', models.IntegerField(blank=True, default=0)),
                ('HCRrooms', models.IntegerField(blank=True, default=0)),
                ('HMrooms', models.IntegerField(blank=True, default=0)),
                ('festivo', models.CharField(blank=True, default='', max_length=30)),
                ('updated', models.DateTimeField()),
                ('precio3stars', models.FloatField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=400)),
                ('entrada', models.DateField()),
                ('salida', models.DateField()),
                ('pax', models.IntegerField(blank=True, default=0)),
                ('dobles', models.IntegerField(blank=True, default=0)),
                ('triples', models.IntegerField(blank=True, default=0)),
                ('DUIs', models.IntegerField(blank=True, default=0)),
                ('singles', models.IntegerField(blank=True, default=0)),
                ('comentarios', models.TextField(blank=True, default='', help_text='Comentarios adicionales', max_length=1000)),
                ('NE', models.BooleanField()),
                ('SA', models.BooleanField()),
                ('AD', models.BooleanField()),
                ('MP', models.BooleanField()),
                ('PC', models.BooleanField()),
                ('reservado', models.CharField(blank=True, choices=[('HCR', 'Reservado en HCR'), ('HCL', 'Reservado en HCL'), ('HM', 'Reservado en HM'), ('CER', 'Cotizado, esperando respuesta'), ('CNR', 'Cotizado, no reserva'), ('SD', 'Sin disponibilidad'), ('NA', 'No atendido')], default='NA', help_text='Estado del grupo', max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Solicitud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100)),
                ('comentarios', models.CharField(blank=True, max_length=1000)),
                ('recibida', models.DateField()),
                ('registrada', models.DateField()),
                ('solicitudHCR', models.BooleanField(default=False)),
                ('solicitudHCL', models.BooleanField(default=False)),
                ('solicitudHM', models.BooleanField(default=False)),
                ('status', models.CharField(blank=True, choices=[('d', 'En duda'), ('n', 'No recibe respuesta'), ('p', 'Pendiente'), ('r', 'Respondida'), ('R', 'Reservada (borrar)')], default='p', help_text='Estado de la solicitud', max_length=1)),
                ('agencia', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.agencia')),
                ('calendario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.calendar')),
                ('grupo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.grupo')),
            ],
            options={
                'ordering': ['registrada'],
            },
        ),
        migrations.CreateModel(
            name='Cotizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cotizacionSA', models.FloatField(blank=True, default=0)),
                ('cotizacionHAB', models.FloatField(blank=True, default=0)),
                ('cotizacionAD', models.FloatField(blank=True, default=0)),
                ('cotizacionMP', models.FloatField(blank=True, default=0)),
                ('cotizacionPC', models.FloatField(blank=True, default=0)),
                ('num_reserva', models.CharField(blank=True, default=0, max_length=20)),
                ('hotel', models.CharField(choices=[('HCR', 'Hotel Carlton Rioja'), ('HCL', 'Hotel Ciudad de Logroño'), ('HM', 'Hotel Murrieta')], default='HM', help_text='Hotel que envía la solicitud', max_length=3)),
                ('enviada', models.DateField(blank=True)),
                ('reservada', models.BooleanField(default=False)),
                ('solicitud', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.solicitud')),
            ],
        ),
    ]
