# Generated by Django 3.2 on 2021-09-02 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cotizacion',
            name='hotel',
            field=models.CharField(blank=True, choices=[('HCR', 'Hotel Carlton Rioja'), ('HCL', 'Hotel Ciudad de Logroño'), ('HM', 'Hotel Murrieta')], default='HM', help_text='Hotel que envía la solicitud', max_length=3),
        ),
        migrations.AlterField(
            model_name='cotizacion',
            name='reservada',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
