# Generated by Django 3.2 on 2021-08-31 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210831_0936'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grupo',
            name='regimen',
        ),
        migrations.AddField(
            model_name='grupo',
            name='AD',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='grupo',
            name='MP',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='grupo',
            name='NE',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='grupo',
            name='PC',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='grupo',
            name='SA',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
