# Generated by Django 3.2 on 2021-09-02 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20210902_1720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cotizacion',
            name='enviada',
            field=models.DateField(blank=True, null=True),
        ),
    ]
