# Generated by Django 3.2 on 2021-09-01 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20210831_1733'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calendar',
            name='price',
        ),
        migrations.RemoveField(
            model_name='calendar',
            name='rooms',
        ),
        migrations.AddField(
            model_name='calendar',
            name='HCLprice',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='calendar',
            name='HCLrooms',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='calendar',
            name='HCRprice',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='calendar',
            name='HCRrooms',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='calendar',
            name='HMprice',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='calendar',
            name='HMrooms',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='calendar',
            name='FyGprice',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='calendar',
            name='NHprice',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.DeleteModel(
            name='Cotizacion',
        ),
    ]
