# Generated by Django 3.2 on 2021-09-03 10:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_cotizacion_enviada'),
    ]

    operations = [
        migrations.AddField(
            model_name='grupo',
            name='enviada',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='status',
            field=models.CharField(blank=True, choices=[('d', 'Cotizada pero no va a reservar'), ('n', 'Sin disponibilidad'), ('p', 'Pendiente'), ('r', 'Cotizada, podría reservar'), ('R', 'Reservada (borrar)'), ('A', 'Reservada y anulada')], default='p', help_text='Estado de la solicitud', max_length=1),
        ),
    ]
