# Generated by Django 3.2 on 2021-09-04 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20210904_1422'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calendar',
            name='FyGprice_lastmonth',
        ),
        migrations.RemoveField(
            model_name='calendar',
            name='FyGprice_lastupdate',
        ),
        migrations.RemoveField(
            model_name='calendar',
            name='FyGprice_lastweek',
        ),
        migrations.RemoveField(
            model_name='calendar',
            name='HCLprice_lastmonth',
        ),
        migrations.RemoveField(
            model_name='calendar',
            name='HCLprice_lastupdate',
        ),
        migrations.RemoveField(
            model_name='calendar',
            name='HCLprice_lastweek',
        ),
        migrations.RemoveField(
            model_name='calendar',
            name='HCLrooms_lastmonth',
        ),
        migrations.RemoveField(
            model_name='calendar',
            name='HCLrooms_lastupdate',
        ),
        migrations.RemoveField(
            model_name='calendar',
            name='HCLrooms_lastweek',
        ),
        migrations.RemoveField(
            model_name='calendar',
            name='HCRprice_lastmonth',
        ),
        migrations.RemoveField(
            model_name='calendar',
            name='HCRprice_lastupdate',
        ),
        migrations.RemoveField(
            model_name='calendar',
            name='HCRprice_lastweek',
        ),
        migrations.RemoveField(
            model_name='calendar',
            name='HCRrooms_lastmonth',
        ),
        migrations.RemoveField(
            model_name='calendar',
            name='HCRrooms_lastupdate',
        ),
        migrations.RemoveField(
            model_name='calendar',
            name='HCRrooms_lastweek',
        ),
        migrations.RemoveField(
            model_name='calendar',
            name='HMprice_lastmonth',
        ),
        migrations.RemoveField(
            model_name='calendar',
            name='HMprice_lastupdate',
        ),
        migrations.RemoveField(
            model_name='calendar',
            name='HMprice_lastweek',
        ),
        migrations.RemoveField(
            model_name='calendar',
            name='HMrooms_lastmonth',
        ),
        migrations.RemoveField(
            model_name='calendar',
            name='HMrooms_lastupdate',
        ),
        migrations.RemoveField(
            model_name='calendar',
            name='HMrooms_lastweek',
        ),
        migrations.RemoveField(
            model_name='calendar',
            name='NHprice_lastmonth',
        ),
        migrations.RemoveField(
            model_name='calendar',
            name='NHprice_lastupdate',
        ),
        migrations.RemoveField(
            model_name='calendar',
            name='NHprice_lastweek',
        ),
    ]
