# Generated by Django 3.2 on 2021-09-04 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20210904_1515'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendar',
            name='FyGprice_lastmonth',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='calendar',
            name='FyGprice_lastupdate',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='calendar',
            name='FyGprice_lastweek',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='calendar',
            name='HCLprice_lastmonth',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='calendar',
            name='HCLprice_lastupdate',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='calendar',
            name='HCLprice_lastweek',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='calendar',
            name='HCLrooms_lastmonth',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='calendar',
            name='HCLrooms_lastupdate',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='calendar',
            name='HCLrooms_lastweek',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='calendar',
            name='HCRprice_lastmonth',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='calendar',
            name='HCRprice_lastupdate',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='calendar',
            name='HCRprice_lastweek',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='calendar',
            name='HCRrooms_lastmonth',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='calendar',
            name='HCRrooms_lastupdate',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='calendar',
            name='HCRrooms_lastweek',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='calendar',
            name='HMprice_lastmonth',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='calendar',
            name='HMprice_lastupdate',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='calendar',
            name='HMprice_lastweek',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='calendar',
            name='HMrooms_lastmonth',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='calendar',
            name='HMrooms_lastupdate',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='calendar',
            name='HMrooms_lastweek',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='calendar',
            name='NHprice_lastmonth',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='calendar',
            name='NHprice_lastupdate',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='calendar',
            name='NHprice_lastweek',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
