# Generated by Django 3.2 on 2021-09-07 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20210907_1011'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitud',
            name='asuntocorreo',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='comentarios',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='correo',
            field=models.TextField(blank=True),
        ),
    ]
