# Generated by Django 3.2 on 2021-09-08 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_auto_20210907_1949'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cotizacion',
            old_name='disponibilidad',
            new_name='disponibilidadHCL',
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='disponibilidadHCR',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='disponibilidadHM',
            field=models.BooleanField(default=True),
        ),
    ]
