# Generated by Django 3.2 on 2021-09-08 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_auto_20210908_1300'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cotizacion',
            old_name='disponibilidadHCL',
            new_name='sindisponibilidad',
        ),
        migrations.RemoveField(
            model_name='cotizacion',
            name='disponibilidadHCR',
        ),
        migrations.RemoveField(
            model_name='cotizacion',
            name='disponibilidadHM',
        ),
    ]
